services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: obscura-app
    container_name: obscura-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:80"
    volumes:
      - obscura-db:/var/www/database
      - obscura-storage:/var/www/storage
    env_file:
      - .env
    networks:
      - obscura

networks:
  obscura:
    driver: bridge

volumes:
  obscura-db:
  obscura-storage: