services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: obscura-app
    container_name: obscura-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - obscura

networks:
  obscura:
    driver: bridge
